# Generated by Django 5.2.3 on 2026-02-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('current_website', models.URLField(blank=True, null=True)),
                ('service_needed', models.CharField(choices=[('new_website', 'New Website Design'), ('redesign', 'Website Redesign'), ('web_app', 'Web Application'), ('maintenance', 'Maintenance & Support'), ('ecommerce', 'E-Commerce Platform'), ('performance', 'Performance Optimization'), ('not_sure', 'Not Sure Yet')], max_length=50)),
                ('project_description', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
